version: '3.4'

services:
  serviceone:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  servicetwo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

